### ISSUE TITLE
Etiquetas

### ISSUE THREAD

**Issue by davo** [gcba/mapa-emprendedores#23]
Modificar

- **Gobierno Nacional** reemplazarlo por **Programas Públicos**
- Espacios de **Coworking** reemplazarlo por **Espacios de Trabajo Colaborativo**
- **Maker space** reemplazarlo por **Espacio de Cocreación**
- **Organización** reemplazarlo por **Institución**

Crear

- Etiqueta **academia**

**Comment by nlound** [comment]
Necesito acceso a CartoDB para cambiar las keywords también

**Comment by nlound** [comment]
Cambio hecho. Falta acceso al legacy para publicar (en gestión) y depurar la db.

**Comment by nlound** [comment]
base depurada. Subir al legacy. Falta icono de academia

**Comment by nlound** [comment]
Closed. f9726ce44150ebbc3a81e50e72c14d8a27895f85
