### ISSUE TITLE
Formulario

### ISSUE THREAD

**Issue by davo** [gcba/mapa-emprendedores#24]
Modificación

- Mensaje "**Aquí se verá ubicado su emprendimiento**", debe agregarse "**Por favor verifique que se corresponda con su domicilio.**"

- "**Responsable del proyecto**" debe decir "**Persona de contacto**" y donde dice "**Mail del responsable**" debe decir "**Mail de Contacto**".

- Campos **Persona de contacto** y **Mail del responsable** serán obligatorios.
  
Revisión de campos

- **Nombre***
- **Descripción***
- **Inicio de actividades***
- Tags
- **Tipo***
- **Sector***
- **Dirección***
- Piso y departamento
- Mail institucional
- Teléfono
- Página web
- **Persona de contacto***
- **Mail de contacto***

Agregar "*" en los campos obligatorios.

**Comment by nlound** [comment]
closed #0f306e988d107fa1f0db5e50b79c983b866a20a5

**Comment by nlound** [comment]
0f306e988d107fa1f0db5e50b79c983b866a20a5

**Comment by nlound** [comment]
closed 0f306e988d107fa1f0db5e50b79c983b866a20a5
