### ISSUE TITLE
Filtros

### ISSUE THREAD

**Issue by davo** [gcba/mapa-emprendedores#25]
Cambio

- **Tipo de industria** cambia por **Tipo de Organización**. 

Agregar (falta contenido)

- Tooltip explicando cada tipo de filtro.

**Comment by nlound** [comment]
Necesito el texto de cada tooltip para implementarlo.

**Comment by nlound** [comment]
closed: 6070aa44d9e3049a85b3ae764d1d6fd885a7485b :+1:
